ALTER TABLE "doctors" ADD COLUMN IF NOT EXISTS "serialLive" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "doctors" ADD COLUMN IF NOT EXISTS "liveCurrentSerial" INTEGER;
ALTER TABLE "doctors" ADD COLUMN IF NOT EXISTS "liveUpdatedAt" TIMESTAMP(3);
