services:
  postgres_db:
    image: postgres:16-alpine
    container_name: express_postgres_container_mrdoctor
    environment:
      POSTGRES_USER: "mrdoctor"
      POSTGRES_PASSWORD: "0237848923723984"
      POSTGRES_DB: "mrdoctor"
    ports:
      - "5432:5432"
    volumes:
      - pg_express_data_mrdoctor:/var/lib/postgresql/data

volumes:
  pg_express_data_mrdoctor: