// src/controllers/doctors/DoctorsController.ts
import type { Response } from 'express';
import { prisma } from '../../lib/prisma.js';
import { AuthRequest } from '../../middleware/authMiddleware.js';

export const seedDoctors = async (req: AuthRequest, res: Response) => {
  try {
    console.log('🔍 ===== START SEEDING NILPHAMARI DOCTORS =====');

    const userId = req.userId || (req as any).user?.id || (req as any).user?.userId;

    if (!userId) {
      return res.status(401).json({
        success: false,
        error: 'User not authenticated'
      });
    }

    const doctorsData = [
      // ==================== Nilphamari Sadar (18 doctors) ====================
      {
        name: "ডা. মো. সামিউর রহমান শাহ্ (সামি)",
        username: "dr-samiur-rahman-shah",
        email: "samiur.rahman@doctors.com",
        degree: "MBBS, BCS (Health), MD (Cardiology), FCPS (Medicine-FP), MACP (USA), CCD",
        speciality: "হৃদরোগ, মেডিসিন ও ডায়াবেটিস বিশেষজ্ঞ",
        tagline: "হৃদরোগ, মেডিসিন ও ডায়াবেটিস বিশেষজ্ঞ",
        bio: "জাতীয় হৃদরোগ ইনস্টিটিউট ও হাসপাতাল, ঢাকা / এ আর জেনারেল হাসপাতাল, নীলফামারী",
        phone: "01733077000",
      },
      {
        name: "ডা. সৈয়দ হাসান আলী",
        username: "dr-hasan-ali",
        email: "hasan.ali@doctors.com",
        degree: "MBBS, D-Ortho (NITOR)",
        speciality: "হাড়, জোড় ও ট্রমা সার্জন",
        tagline: "হাড়, জোড় ও ট্রমা সার্জন",
        bio: "পঙ্গু হাসপাতাল, ঢাকা / এ আর জেনারেল হাসপাতাল, নীলফামারী",
        phone: "01733077001",
      },
      {
        name: "ডা. মো. মনিরুজ্জামান (মনি)",
        username: "dr-moniruzzaman",
        email: "moniruzzaman@doctors.com",
        degree: "MBBS, BCS (Health), CCD (BIRDEM), CMU",
        speciality: "মেডিসিন, ডায়াবেটিস ও সনোলজিস্ট",
        tagline: "মেডিসিন, ডায়াবেটিস ও সনোলজিস্ট",
        bio: "২৫০ শয্যা বিশিষ্ট জেনারেল হাসপাতাল, নীলফামারী",
        phone: "01733077002",
      },
      {
        name: "ডা. মো. রেজাউল করিম",
        username: "dr-rezaul-karim",
        email: "rezaul.karim@doctors.com",
        degree: "MBBS, BCS (Health), CCD (BIRDEM)",
        speciality: "মেডিসিন ও ডায়াবেটিস বিশেষজ্ঞ",
        tagline: "মেডিসিন ও ডায়াবেটিস বিশেষজ্ঞ",
        bio: "২৫০ শয্যা বিশিষ্ট জেনারেল হাসপাতাল, নীলফামারী",
        phone: "01733077003",
      },
      {
        name: "ডা. মো. মিনহাজ উদ্দিন রাজীব",
        username: "dr-minhaj-uddin-rajib",
        email: "minhaj.uddin@doctors.com",
        degree: "MBBS, BCS (Health), FCPS (Surgery)",
        speciality: "জেনারেল ও ল্যাপারোস্কোপিক সার্জন",
        tagline: "জেনারেল ও ল্যাপারোস্কোপিক সার্জন",
        bio: "২৫০ শয্যা বিশিষ্ট জেনারেল হাসপাতাল, নীলফামারী",
        phone: "01733077004",
      },
      {
        name: "ডা. মো. ময়নুল হক চৌধুরী",
        username: "dr-moynul-haque-chowdhury",
        email: "moynul.haque@doctors.com",
        degree: "MBBS, BCS (Health), CPA (USA)",
        speciality: "কিডনি রোগ বিশেষজ্ঞ (নেফ্রোলজিস্ট)",
        tagline: "কিডনি রোগ বিশেষজ্ঞ (নেফ্রোলজিস্ট)",
        bio: "নীলফামারী মেডিকেল কলেজ ও হাসপাতাল",
        phone: "01733077005",
      },
      {
        name: "ডা. মোছা: হাসিনা বানু",
        username: "dr-hasina-banu",
        email: "hasina.banu@doctors.com",
        degree: "MBBS, BCS (Health), FCPS (Gynae & Obs)",
        speciality: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        bio: "২৫০ শয্যা বিশিষ্ট জেনারেল হাসপাতাল, নীলফামারী",
        phone: "01733077006",
      },
      {
        name: "ডা. রূপায়ন দাশ",
        username: "dr-rupayan-das",
        email: "rupayan.das@doctors.com",
        degree: "MBBS, BCS (Health), D-Ortho",
        speciality: "অর্থোপেডিক ও ট্রমা সার্জন",
        tagline: "অর্থোপেডিক ও ট্রমা সার্জন",
        bio: "২৫০ শয্যা বিশিষ্ট জেনারেল হাসপাতাল, নীলফামারী",
        phone: "01733077007",
      },
      {
        name: "ডা. আনছার আলী",
        username: "dr-ansar-ali",
        email: "ansar.ali@doctors.com",
        degree: "MBBS, DCO, Fellow IOL",
        speciality: "চক্ষু রোগ বিশেষজ্ঞ ও সার্জন",
        tagline: "চক্ষু রোগ বিশেষজ্ঞ ও সার্জন",
        bio: "ইসলামিয়া আই হসপিটাল, নীলফামারী",
        phone: "01733077008",
      },
      {
        name: "ডা. মুহাম্মদ লিটন খন্দকার",
        username: "dr-liton-khandaker",
        email: "liton.khandaker@doctors.com",
        degree: "MBBS, BCS (Health), FCPS (ENT)",
        speciality: "নাক, কান ও গলা বিশেষজ্ঞ",
        tagline: "নাক, কান ও গলা বিশেষজ্ঞ",
        bio: "সদর হাসপাতাল, নীলফামারী",
        phone: "01733077009",
      },
      {
        name: "ডা. মো. মহিমিনুল ইসলাম",
        username: "dr-mahiminul-islam",
        email: "mahiminul.islam@doctors.com",
        degree: "MBBS, Diploma in Dermatology",
        speciality: "চর্ম, অ্যালার্জি ও যৌন রোগ বিশেষজ্ঞ",
        tagline: "চর্ম, অ্যালার্জি ও যৌন রোগ বিশেষজ্ঞ",
        bio: "মডার্ন ডায়াগনস্টিক সেন্টার, নীলফামারী",
        phone: "01733077010",
      },
      {
        name: "ডা. এ.কে.এম. ওয়াজেদ আলী",
        username: "dr-wazed-ali",
        email: "wazed.ali@doctors.com",
        degree: "MBBS, FCPS (Surgery)",
        speciality: "জেনারেল ও ল্যাপারোস্কোপিক সার্জন",
        tagline: "জেনারেল ও ল্যাপারোস্কোপিক সার্জন",
        bio: "শহীদ ডাক্তার শামসুল হক হসপিটাল, সৈয়দপুর",
        phone: "01717000001",
      },
      {
        name: "ডা. মো. মোস্তাফিজুর রহমান",
        username: "dr-mostafizur-rahman",
        email: "mostafizur.rahman@doctors.com",
        degree: "MBBS, MD (Chest)",
        speciality: "বক্ষব্যাধি, হাঁপানি ও টিবি বিশেষজ্ঞ",
        tagline: "বক্ষব্যাধি, হাঁপানি ও টিবি বিশেষজ্ঞ",
        bio: "১০০ শয্যা বিশিষ্ট হাসপাতাল, সৈয়দপুর",
        phone: "01717000002",
      },
      {
        name: "ডা. সেলিনা পারভীন মিলি",
        username: "dr-selina-parvin-mili",
        email: "selina.parvin@doctors.com",
        degree: "MBBS, FCPS (Gynae)",
        speciality: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        bio: "সৈয়দপুর ডায়াবেটিক ও ম্যাটার্নিটি হসপিটাল",
        phone: "01717000003",
      },
      {
        name: "ডা. বিপ্লব কুমার সরকার",
        username: "dr-biplob-kumar-sarker",
        email: "biplob.sarker@doctors.com",
        degree: "MBBS, MS (Orthopedics)",
        speciality: "অর্থোপেডিক ও ট্রমা সার্জন",
        tagline: "অর্থোপেডিক ও ট্রমা সার্জন",
        bio: "সৈয়দপুর আধুনিক হাসপাতাল",
        phone: "01717000004",
      },
      {
        name: "ডা. মো. গোলাম মোস্তফা",
        username: "dr-golam-mostafa",
        email: "golam.mostafa@doctors.com",
        degree: "MBBS, DCH (Pediatrics)",
        speciality: "শিশু রোগ বিশেষজ্ঞ",
        tagline: "শিশু রোগ বিশেষজ্ঞ",
        bio: "১০০ শয্যা বিশিষ্ট হাসপাতাল, সৈয়দপুর",
        phone: "01717000005",
      },
      {
        name: "ডা. শাহানাজ পারভীন",
        username: "dr-shahanaz-parvin",
        email: "shahanaz.parvin@doctors.com",
        degree: "MBBS, FCPS (Skin & VD)",
        speciality: "চর্ম ও যৌন রোগ বিশেষজ্ঞ",
        tagline: "চর্ম ও যৌন রোগ বিশেষজ্ঞ",
        bio: "সৈয়দপুর স্পেশালিষ্ট ক্লিনিক",
        phone: "01717000006",
      },
      {
        name: "ডা. কে. এম. রেজাউল করিম",
        username: "dr-km-rezaul-karim",
        email: "km.rezaul.karim@doctors.com",
        degree: "MBBS, MS (ENT)",
        speciality: "নাক, কান ও গলা বিশেষজ্ঞ",
        tagline: "নাক, কান ও গলা বিশেষজ্ঞ",
        bio: "সৈয়দপুর ইসলামী ব্যাংক কমিউনিটি হসপিটাল",
        phone: "01717000007",
      },

      // ==================== Domar (5 doctors) ====================
      {
        name: "ডা. আব্দুল্লাহ আল মামুন",
        username: "dr-abdullah-al-mamun",
        email: "abdullah.mamun@doctors.com",
        degree: "MBBS, BCS (Health), MD (Medicine)",
        speciality: "মেডিসিন বিশেষজ্ঞ",
        tagline: "মেডিসিন বিশেষজ্ঞ",
        bio: "ডোমার উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077011",
      },
      {
        name: "ডা. নাজমা আক্তার",
        username: "dr-nazma-akter",
        email: "nazma.akter@doctors.com",
        degree: "MBBS, DGO",
        speciality: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        bio: "ডোমার উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077012",
      },
      {
        name: "ডা. মো. শহিদুল ইসলাম",
        username: "dr-shahidul-islam",
        email: "shahidul.islam@doctors.com",
        degree: "MBBS, FCPS (Surgery)",
        speciality: "জেনারেল সার্জন",
        tagline: "জেনারেল সার্জন",
        bio: "ডোমার ডায়াবেটিক ক্লিনিক, নীলফামারী",
        phone: "01733077013",
      },
      {
        name: "ডা. সুমন কুমার দাস",
        username: "dr-sumon-kumar-das",
        email: "sumon.das@doctors.com",
        degree: "MBBS, D-Ortho",
        speciality: "অর্থোপেডিক সার্জন",
        tagline: "অর্থোপেডিক সার্জন",
        bio: "ডোমার আধুনিক হাসপাতাল, নীলফামারী",
        phone: "01733077014",
      },
      {
        name: "ডা. রোকসানা খাতুন",
        username: "dr-roksana-khatun",
        email: "roksana.khatun@doctors.com",
        degree: "MBBS, DCH",
        speciality: "শিশু রোগ বিশেষজ্ঞ",
        tagline: "শিশু রোগ বিশেষজ্ঞ",
        bio: "ডোমার উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077015",
      },

      // ==================== Jaldhaka (5 doctors) ====================
      {
        name: "ডা. মো. শাহজাহান আলী",
        username: "dr-shahjahan-ali",
        email: "shahjahan.ali@doctors.com",
        degree: "MBBS, BCS (Health), MD (Cardiology)",
        speciality: "হৃদরোগ বিশেষজ্ঞ",
        tagline: "হৃদরোগ বিশেষজ্ঞ",
        bio: "জলঢাকা উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077016",
      },
      {
        name: "ডা. ফাতেমা বেগম",
        username: "dr-fatema-begum",
        email: "fatema.begum@doctors.com",
        degree: "MBBS, FCPS (Gynae)",
        speciality: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        bio: "জলঢাকা উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077017",
      },
      {
        name: "ডা. মো. আব্দুল কাদের",
        username: "dr-abdul-kader",
        email: "abdul.kader@doctors.com",
        degree: "MBBS, MS (ENT)",
        speciality: "নাক, কান ও গলা বিশেষজ্ঞ",
        tagline: "নাক, কান ও গলা বিশেষজ্ঞ",
        bio: "জলঢাকা হাসপাতাল, নীলফামারী",
        phone: "01733077018",
      },
      {
        name: "ডা. মেরিনা সুলতানা",
        username: "dr-merina-sultana",
        email: "merina.sultana@doctors.com",
        degree: "MBBS, DCP",
        speciality: "প্যাথলজি বিশেষজ্ঞ",
        tagline: "প্যাথলজি বিশেষজ্ঞ",
        bio: "জলঢাকা ডায়াগনস্টিক সেন্টার, নীলফামারী",
        phone: "01733077019",
      },
      {
        name: "ডা. মো. ফরহাদ হোসেন",
        username: "dr-farhad-hossain",
        email: "farhad.hossain@doctors.com",
        degree: "MBBS, BCS (Health), CCD",
        speciality: "ডায়াবেটিস ও মেডিসিন বিশেষজ্ঞ",
        tagline: "ডায়াবেটিস ও মেডিসিন বিশেষজ্ঞ",
        bio: "জলঢাকা উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077020",
      },

      // ==================== Kishoreganj (5 doctors) ====================
      {
        name: "ডা. মো. আবু বাক্কার সিদ্দিক",
        username: "dr-abu-bakkar-siddik",
        email: "abu.bakkar@doctors.com",
        degree: "MBBS, BCS (Health), MD (Medicine)",
        speciality: "মেডিসিন বিশেষজ্ঞ",
        tagline: "মেডিসিন বিশেষজ্ঞ",
        bio: "কিশোরগঞ্জ উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077021",
      },
      {
        name: "ডা. মোসাম্মত নাসিমা আক্তার",
        username: "dr-nasima-akter",
        email: "nasima.akter@doctors.com",
        degree: "MBBS, FCPS (Gynae & Obs)",
        speciality: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        bio: "কিশোরগঞ্জ উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077022",
      },
      {
        name: "ডা. মো. রফিকুল ইসলাম",
        username: "dr-rafiqul-islam",
        email: "rafiqul.islam@doctors.com",
        degree: "MBBS, FCPS (Surgery)",
        speciality: "জেনারেল সার্জন",
        tagline: "জেনারেল সার্জন",
        bio: "কিশোরগঞ্জ কমিউনিটি হাসপাতাল, নীলফামারী",
        phone: "01733077023",
      },
      {
        name: "ডা. মো. ইসমাইল হোসেন",
        username: "dr-ismail-hossain",
        email: "ismail.hossain@doctors.com",
        degree: "MBBS, D-Ortho",
        speciality: "অর্থোপেডিক সার্জন",
        tagline: "অর্থোপেডিক সার্জন",
        bio: "কিশোরগঞ্জ উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077024",
      },
      {
        name: "ডা. হোসনে আরা বেগম",
        username: "dr-hosne-ara-begum",
        email: "hosne.ara@doctors.com",
        degree: "MBBS, DCH",
        speciality: "শিশু রোগ বিশেষজ্ঞ",
        tagline: "শিশু রোগ বিশেষজ্ঞ",
        bio: "কিশোরগঞ্জ শিশু ক্লিনিক, নীলফামারী",
        phone: "01733077025",
      },

      // ==================== Saidpur additional (5 doctors) ====================
      {
        name: "ডা. মো. নজরুল ইসলাম",
        username: "dr-nazrul-islam",
        email: "nazrul.islam@doctors.com",
        degree: "MBBS, BCS (Health), MD (Cardiology)",
        speciality: "হৃদরোগ বিশেষজ্ঞ",
        tagline: "হৃদরোগ বিশেষজ্ঞ",
        bio: "সৈয়দপুর ১০০ শয্যা বিশিষ্ট হাসপাতাল, নীলফামারী",
        phone: "01733077026",
      },
      {
        name: "ডা. লায়লা খানম",
        username: "dr-laila-khanam",
        email: "laila.khanam@doctors.com",
        degree: "MBBS, FCPS (Medicine)",
        speciality: "মেডিসিন বিশেষজ্ঞ",
        tagline: "মেডিসিন বিশেষজ্ঞ",
        bio: "সৈয়দপুর জেনারেল হাসপাতাল, নীলফামারী",
        phone: "01733077027",
      },
      {
        name: "ডা. মো. আব্দুল মান্নান",
        username: "dr-abdul-mannan",
        email: "abdul.mannan@doctors.com",
        degree: "MBBS, MS (Orthopedics)",
        speciality: "অর্থোপেডিক ও ট্রমা সার্জন",
        tagline: "অর্থোপেডিক ও ট্রমা সার্জন",
        bio: "সৈয়দপুর অর্থোপেডিক সেন্টার, নীলফামারী",
        phone: "01733077028",
      },
      {
        name: "ডা. পারভীন সুলতানা",
        username: "dr-parvin-sultana",
        email: "parvin.sultana@doctors.com",
        degree: "MBBS, DGO, FCPS (Gynae)",
        speciality: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        bio: "সৈয়দপুর ম্যাটার্নিটি ক্লিনিক, নীলফামারী",
        phone: "01733077029",
      },
      {
        name: "ডা. মো. আবুল কালাম আজাদ",
        username: "dr-abul-kalam-azad",
        email: "abul.kalam@doctors.com",
        degree: "MBBS, FCPS (ENT)",
        speciality: "নাক, কান ও গলা বিশেষজ্ঞ",
        tagline: "নাক, কান ও গলা বিশেষজ্ঞ",
        bio: "সৈয়দপুর ইসলামী ব্যাংক কমিউনিটি হসপিটাল, নীলফামারী",
        phone: "01733077030",
      },

      // ==================== Dimla (3 doctors) ====================
      {
        name: "ডা. মো. শহীদুল্লাহ",
        username: "dr-shahidullah",
        email: "shahidullah@doctors.com",
        degree: "MBBS, BCS (Health), MD (Medicine)",
        speciality: "মেডিসিন বিশেষজ্ঞ",
        tagline: "মেডিসিন বিশেষজ্ঞ",
        bio: "ডিমলা উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077031",
      },
      {
        name: "ডা. ছালেহা খাতুন",
        username: "dr-saleha-khatun",
        email: "saleha.khatun@doctors.com",
        degree: "MBBS, FCPS (Gynae)",
        speciality: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ ও প্রসূতিবিদ্যা বিশেষজ্ঞ",
        bio: "ডিমলা উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077032",
      },
      {
        name: "ডা. মো. এনামুল হক",
        username: "dr-enamul-haque",
        email: "enamul.haque@doctors.com",
        degree: "MBBS, D-Ortho",
        speciality: "অর্থোপেডিক সার্জন",
        tagline: "অর্থোপেডিক সার্জন",
        bio: "ডিমলা আধুনিক হাসপাতাল, নীলফামারী",
        phone: "01733077033",
      },

      // ==================== Water Management (3 doctors) ====================
      {
        name: "ডা. মো. আব্দুর রহিম",
        username: "dr-abdur-rahim",
        email: "abdur.rahim@doctors.com",
        degree: "MBBS, BCS (Health), MD (Cardiology)",
        speciality: "হৃদরোগ বিশেষজ্ঞ",
        tagline: "হৃদরোগ বিশেষজ্ঞ",
        bio: "পানি ব্যবস্থাপনা হাসপাতাল, নীলফামারী",
        phone: "01733077034",
      },
      {
        name: "ডা. সুরাইয়া বেগম",
        username: "dr-suraiya-begum",
        email: "suraiya.begum@doctors.com",
        degree: "MBBS, FCPS (Gynae)",
        speciality: "স্ত্রী রোগ বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ বিশেষজ্ঞ",
        bio: "পানি ব্যবস্থাপনা স্বাস্থ্য কেন্দ্র, নীলফামারী",
        phone: "01733077035",
      },
      {
        name: "ডা. মো. সাইফুল ইসলাম",
        username: "dr-saiful-islam",
        email: "saiful.islam@doctors.com",
        degree: "MBBS, MS (Orthopedics)",
        speciality: "অর্থোপেডিক সার্জন",
        tagline: "অর্থোপেডিক সার্জন",
        bio: "পানি ব্যবস্থাপনা হাসপাতাল, নীলফামারী",
        phone: "01733077036",
      },

      // ==================== Sonakata (3 doctors) ====================
      {
        name: "ডা. মো. আবু হেনা মোস্তফা",
        username: "dr-abu-hena-mostafa",
        email: "abu.hena@doctors.com",
        degree: "MBBS, BCS (Health), MD (Medicine)",
        speciality: "মেডিসিন বিশেষজ্ঞ",
        tagline: "মেডিসিন বিশেষজ্ঞ",
        bio: "সোনাকাটা উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077037",
      },
      {
        name: "ডা. নাহিদা বেগম",
        username: "dr-nahida-begum",
        email: "nahida.begum@doctors.com",
        degree: "MBBS, FCPS (Gynae)",
        speciality: "স্ত্রী রোগ বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ বিশেষজ্ঞ",
        bio: "সোনাকাটা উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077038",
      },
      {
        name: "ডা. মো. আব্দুর রউফ",
        username: "dr-abdur-rauf",
        email: "abdur.rauf@doctors.com",
        degree: "MBBS, D-Ortho",
        speciality: "অর্থোপেডিক সার্জন",
        tagline: "অর্থোপেডিক সার্জন",
        bio: "সোনাকাটা হাসপাতাল, নীলফামারী",
        phone: "01733077039",
      },

      // ==================== Milan (3 doctors) ====================
      {
        name: "ডা. মো. দেলোয়ার হোসেন",
        username: "dr-delwar-hossain",
        email: "delwar.hossain@doctors.com",
        degree: "MBBS, BCS (Health), MD (Cardiology)",
        speciality: "হৃদরোগ বিশেষজ্ঞ",
        tagline: "হৃদরোগ বিশেষজ্ঞ",
        bio: "মিলান উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077040",
      },
      {
        name: "ডা. আফরোজা বেগম",
        username: "dr-afroza-begum",
        email: "afroza.begum@doctors.com",
        degree: "MBBS, FCPS (Gynae)",
        speciality: "স্ত্রী রোগ বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ বিশেষজ্ঞ",
        bio: "মিলান উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077041",
      },
      {
        name: "ডা. মো. জাহাঙ্গীর আলম",
        username: "dr-jahangir-alam",
        email: "jahangir.alam@doctors.com",
        degree: "MBBS, FCPS (Surgery)",
        speciality: "জেনারেল সার্জন",
        tagline: "জেনারেল সার্জন",
        bio: "মিলান হাসপাতাল, নীলফামারী",
        phone: "01733077042",
      },

      // ==================== Bhandarkuthi (2 doctors) ====================
      {
        name: "ডা. মো. ইব্রাহিম খলিল",
        username: "dr-ibrahim-khalil",
        email: "ibrahim.khalil@doctors.com",
        degree: "MBBS, BCS (Health), MD (Medicine)",
        speciality: "মেডিসিন বিশেষজ্ঞ",
        tagline: "মেডিসিন বিশেষজ্ঞ",
        bio: "ভান্ডারকুঠি উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077043",
      },
      {
        name: "ডা. শামিমা নাসরিন",
        username: "dr-shamima-nasrin",
        email: "shamima.nasrin@doctors.com",
        degree: "MBBS, DGO",
        speciality: "স্ত্রী রোগ বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ বিশেষজ্ঞ",
        bio: "ভান্ডারকুঠি উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077044",
      },

      // ==================== Barabari (2 doctors) ====================
      {
        name: "ডা. মো. আব্দুস সামাদ",
        username: "dr-abdus-samad",
        email: "abdus.samad@doctors.com",
        degree: "MBBS, BCS (Health), MD (Cardiology)",
        speciality: "হৃদরোগ বিশেষজ্ঞ",
        tagline: "হৃদরোগ বিশেষজ্ঞ",
        bio: "বড়বাড়ি উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077045",
      },
      {
        name: "ডা. নুরজাহান বেগম",
        username: "dr-nurjahan-begum",
        email: "nurjahan.begum@doctors.com",
        degree: "MBBS, FCPS (Gynae)",
        speciality: "স্ত্রী রোগ বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ বিশেষজ্ঞ",
        bio: "বড়বাড়ি উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077046",
      },

      // ==================== Bhotmari (2 doctors) ====================
      {
        name: "ডা. মো. নুরুল ইসলাম",
        username: "dr-nurul-islam",
        email: "nurul.islam@doctors.com",
        degree: "MBBS, BCS (Health), MD (Medicine)",
        speciality: "মেডিসিন বিশেষজ্ঞ",
        tagline: "মেডিসিন বিশেষজ্ঞ",
        bio: "ভোটমারী উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077047",
      },
      {
        name: "ডা. রাশিদা খাতুন",
        username: "dr-rashida-khatun",
        email: "rashida.khatun@doctors.com",
        degree: "MBBS, DGO",
        speciality: "স্ত্রী রোগ বিশেষজ্ঞ",
        tagline: "স্ত্রী রোগ বিশেষজ্ঞ",
        bio: "ভোটমারী উপজেলা স্বাস্থ্য কমপ্লেক্স, নীলফামারী",
        phone: "01733077048",
      },

      // ==================== Additional doctors (2 doctors) ====================
      {
        name: "ডা. মো. মনোয়ার হোসেন",
        username: "dr-monowar-hossain",
        email: "monowar.hossain@doctors.com",
        degree: "MBBS, FCPS (Surgery)",
        speciality: "জেনারেল ও ল্যাপারোস্কোপিক সার্জন",
        tagline: "জেনারেল ও ল্যাপারোস্কোপিক সার্জন",
        bio: "নীলফামারী আধুনিক হাসপাতাল, নীলফামারী",
        phone: "01733077049",
      },
      {
        name: "ডা. আখতারুন নেসা",
        username: "dr-akhterun-nesa",
        email: "akhterun.nesa@doctors.com",
        degree: "MBBS, FCPS (Skin & VD)",
        speciality: "চর্ম ও যৌন রোগ বিশেষজ্ঞ",
        tagline: "চর্ম ও যৌন রোগ বিশেষজ্ঞ",
        bio: "নীলফামারী স্কিন ক্লিনিক, নীলফামারী",
        phone: "01733077050",
      }
    ];

    const result = await prisma.doctor.createMany({
      data: doctorsData,
      skipDuplicates: true,
    });

    console.log(`✅ ${result.count} টি নীলফামারী জেলার ডাক্তারের ডাটা সফলভাবে যুক্ত করা হয়েছে!`);

    return res.status(201).json({
      success: true,
      count: result.count,
      message: 'সফলভাবে নীলফামারী জেলার বিশেষজ্ঞ ডাক্তারদের ডাটা সিড করা হয়েছে!'
    });

  } catch (error: any) {
    console.error('❌ ERROR seeding Nilphamari doctors:', error);
    return res.status(500).json({
      success: false,
      error: 'Failed to seed Nilphamari doctors',
      details: error.message
    });
  }
};